// import { faker } from '@faker-js/faker';
// import { Store } from 'src/modules/store/entities/store.entity';

// export const createFakeStore = (): Partial<Store> => ({
//   name: faker.company.name(),
//   about: faker.company.catchPhrase(),
//   category: faker.helpers.arrayElement(['bakery', 'supermarket', 'hotel']),
//   mobile_no: faker.phone.number(),
//   alternate_mobile_no: faker.phone.number(),
//   email: faker.internet.email(),
//   street: faker.address.streetAddress(),
//   city: faker.address.city(),
//   state: faker.address.state(),
//   postal_code: faker.address.zipCode(),
//   country: faker.address.country(),
//   open_time: '08:00',
//   close_time: '22:00',
//   owner_id: faker.number.int({ min: 1, max: 100 }),
//   gst_no: `GST${faker.string.alphanumeric(8)}`,
//   acc_no: faker.finance.accountNumber(),
//   ifsc_code: `BANK${faker.string.alphanumeric(8)}`,
//   bank_branch: faker.company.name(),
//   image_url: faker.helpers.arrayElement([
//     'https://newturnwebsolutions.com/images/Image1.jpeg',
//     'https://newturnwebsolutions.com/images/Image2.jpeg',
//     'https://newturnwebsolutions.com/images/Image3.jpeg',
//     'https://newturnwebsolutions.com/images/Image4.jpeg',
//     'https://newturnwebsolutions.com/images/Image5.jpeg',
//     'https://newturnwebsolutions.com/images/Image6.jpeg',
//     'https://newturnwebsolutions.com/images/Image7.jpeg',
//     'https://newturnwebsolutions.com/images/Image8.jpeg',
//     'https://newturnwebsolutions.com/images/Image9.jpeg',
//     'https://newturnwebsolutions.com/images/Image10.jpeg',
//     'https://newturnwebsolutions.com/images/Image11.jpeg',
//     'https://newturnwebsolutions.com/images/Image12.jpeg',
//     'https://newturnwebsolutions.com/images/Image13.jpeg',
//     'https://newturnwebsolutions.com/images/Image14.jpeg',
//   ]),
//   icon_url: faker.helpers.arrayElement([
//     'https://newturnwebsolutions.com/images/Image1.jpeg',
//     'https://newturnwebsolutions.com/images/Image2.jpeg',
//     'https://newturnwebsolutions.com/images/Image3.jpeg',
//     'https://newturnwebsolutions.com/images/Image4.jpeg',
//     'https://newturnwebsolutions.com/images/Image5.jpeg',
//     'https://newturnwebsolutions.com/images/Image6.jpeg',
//     'https://newturnwebsolutions.com/images/Image7.jpeg',
//     'https://newturnwebsolutions.com/images/Image8.jpeg',
//     'https://newturnwebsolutions.com/images/Image9.jpeg',
//     'https://newturnwebsolutions.com/images/Image10.jpeg',
//     'https://newturnwebsolutions.com/images/Image11.jpeg',
//     'https://newturnwebsolutions.com/images/Image12.jpeg',
//     'https://newturnwebsolutions.com/images/Image13.jpeg',
//     'https://newturnwebsolutions.com/images/Image14.jpeg',
//   ]),
//   business_start_date: faker.date.past(),
//   latitude: faker.helpers.arrayElement([13.10676, 13.119575, 13.182804, 13.061561, 13.057214,12.990010  ]),
//   longitude: faker.helpers.arrayElement([80.21386, 80.241242, 80.230984, 80.202149, 80.165414,80.207610]),
// });
